version: "3.2"
services:
  tenant:
    build: 
      context: .
    env_file: 
      - ./.env
    image: bmkrishnasource/tenant-service
    restart: on-failure
    ports: 
      - 7171:7171
    container_name: tenant-service-app
    depends_on: 
      - mysql
    networks:
      - fullstack
      
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_HOST=${DB_HOST} 
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_container:/var/lib/mysql
    networks:
      - fullstack
  
  adminer:
    image: adminer:4.7
    restart: always
    depends_on: 
      - mysql
    ports:
      - 7272:8080
    
      
volumes:
  mysql_container:                   # Uncomment this when using mysql.

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge
    

